include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
  exclude:
    - "**/*.g.dart"    # أمثلة: استثناء ملفات مولدة
    - "build/**"

# إعدادات إضافية (اختياري):
linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true 
    always_use_package_imports: true