import 'package:dartchess/dartchess.dart';

// part 'game_chess_board_state.freezed.dart'; // Generated by freezed
// part 'game_chess_board_state.g.dart';

class ChessBoardState {
  final String fen;
  final String moves;
  final Position position;

  ChessBoardState({
    required this.fen,
    required this.moves,
    required this.position,
  });

  List<ChessBoardState> past = [];
  List<ChessBoardState> future = [];
  void undoMove(ChessBoardState chssBoard) {
    if (past.isEmpty) return;

    future.add(chssBoard);
  }

  void redoMove(ChessBoardState chssBoard) {
    if (future.isEmpty) return;
    past.add(chssBoard);
  }
}
